### ISSUE TITLE
Add Skills Section in Form

### ISSUE THREAD

**Issue by victorchrollo14** [victorchrollo14/CV-APP-React#4]

**Comment by ruby-srijan** [comment]
Can I work on this issue?

**Comment by Ruby-Jain** [comment]
Hi, Can I work on this issue?

**Comment by victorchrollo14** [comment]
well this is an assignment project I was building as a part of  Odin Project React course.
alright you can add the skill section.
![Screenshot from 2023-05-17 22-17-06](https://github.com/victorchrollo14/CV-APP-React/assets/89346667/d99d4a95-7826-4780-8cba-fd68dac30208)

This is how the Design looks like.
Add a Heading -> "Skills"
an input:text  -> for the user to enter their skill
ADD Button -> Onclick would create a new Input:text to enter their skill.
Delete Button -> to delete the latest added input:text.

Something like this.
![Screenshot from 2023-05-18 09-25-41](https://github.com/victorchrollo14/CV-APP-React/assets/89346667/4e629a30-24ba-452c-b65a-f4fff3729d9d)

Here is the design file. You can check it out here.
https://www.figma.com/file/rTQhsCzUCNj8G9RI31t1dT/Job-application-form-(Community)?type=design&node-id=116-60&t=WYvcnnbaFL7Navv2-0

**Comment by Ruby-Jain** [comment]
Okay, let start building it.

**Comment by victorchrollo14** [comment]
alright 👍

**Comment by victorchrollo14** [comment]
when you commit it just write "fix issue #issuenumber".

**Comment by Ruby-Jain** [comment]
Okay

**Comment by victorchrollo14** [comment]
completed
